### ISSUE TITLE
Improve Readme of the project

### ISSUE THREAD

**Issue by ParthS007** [nasa/cmr-metadata-review#3]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Currently, `README.rdoc` is not properly formatted.

**Expected behavior:**
We can use Markdown for properly formatting the `README` which will increase its readability for the reader.

I want to work on this issue.

**Comment by ParthS007** [comment]
Hello Maintainers
Can I proceed with this Issue?
Please confirm so that I can start working on this.
Thanks

**Comment by jceaser** [comment]
this has already been done and can be seen in the dev branch.

**Comment by jceaser** [comment]
thanks for taking a look.
